# Generated by Django 3.2 on 2021-04-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter3', '0002_auto_20210417_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='user_url',
            field=models.URLField(max_length=2000),
        ),
    ]
