# Generated by Django 3.2 on 2021-04-20 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cutter3', '0004_urlshort_num_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
